name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    # This will trigger on all pull requests, regardless of the branch
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build application
        run: npm run build

      - name: Start server in background
        run: npm run start &  # Starts the Next.js app in the background
        env:
          CI: true

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000  # Wait until the server is ready

      - name: Run Cypress tests
        run: npm run cypress:run
        env:
            
            CYPRESS_BASE_URL:  ${{ secrets.PRODUCTION_URL }}
